name: Dependabot add yarn.lock

on:
  pull_request_target:

jobs:
  build:
    name: dependabot_fix
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.head.ref, 'dependabot/npm_and_yarn/')
    # IMPORTANT: setting YARN_ENABLE_SCRIPTS=false is critical to ensure that untrusted
    # PRs can't add an npm package and then use that to execute untrusted code in
    # a trusted context. See links at the top of this workflow for further details.
    # See also: https://github.com/yarnpkg/berry/issues/1679#issuecomment-669937860
    env:
      YARN_ENABLE_SCRIPTS: false
      YARN_ENABLE_IMMUTABLE_INSTALLS: false

    steps:
      - uses: actions/checkout@v2
        with:
          # Using a Personal Access Token here is required to trigger workflows on our new commit.
          # The default GitHub token doesn't trigger any workflows.
          # See: https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854/2
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          # Need fetch-depth in order to soft reset the most recent commit.
          fetch-depth: 2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Undo yarn.lock changes from last commit (if any), run yarn install,
      # and add/commit any yarn.lock changes. Dependabot will commit an invalid
      # yarn.lock file for dependecy changes in the root package.json. `yarn install`
      # will not work with an invalid yarn.lock file.
      - name: Install and commit yarn.lock
        working-directory: .
        run: |
          git config user.name "Hampus Nilsson"
          git config user.email "limstift_88@msn.com"
          git reset --soft HEAD~1
          git restore --staged yarn.lock
          git checkout -- yarn.lock
          yarn install
          git add yarn.lock
          git commit -m '${{ github.event.pull_request.title }}'
          git push -f
